### ISSUE TITLE
pip install fails with "No such file or directory: 'README.rst'"

### ISSUE THREAD

**Issue by stephenmobley** [anentropic/django-tempocal#1]
VERSION: django-tempocal-0.1.2

`pip install django-tempocal` fails when python raises an IOError exception "No such file or directory: 'README.rst'".

It seems the appropriate solution is to add `*.rst` to the recursive-include value in MANIFEST.in. Please advise if there's a better way.

**Comment by anentropic** [comment]
oops, ok thanks for letting me know

**Comment by anentropic** [comment]
fixed in v0.1.3 on pypi now
